"""migrae

Revision ID: 033390058543
Revises: 2d6067530655
Create Date: 2021-02-20 15:32:39.684928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033390058543'
down_revision = '2d6067530655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_like', 'like_flag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_like', sa.Column('like_flag', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
