"""comment migrate

Revision ID: 2c407c296c44
Revises: ec6592914f4d
Create Date: 2021-02-19 15:41:49.648725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c407c296c44'
down_revision = 'ec6592914f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'comment_id')
    # ### end Alembic commands ###
