"""migrate

Revision ID: 2d6067530655
Revises: db4638107282
Create Date: 2021-02-20 15:08:18.493991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6067530655'
down_revision = 'db4638107282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_like', sa.Column('like_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_like', 'like_flag')
    # ### end Alembic commands ###
