"""like_flag migrate

Revision ID: db4638107282
Revises: 2c407c296c44
Create Date: 2021-02-20 14:52:31.781476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4638107282'
down_revision = '2c407c296c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('like_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'like_flag')
    # ### end Alembic commands ###
