"""comment_migrate

Revision ID: ec6592914f4d
Revises: 01db458591bc
Create Date: 2021-02-19 14:48:18.672291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec6592914f4d'
down_revision = '01db458591bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('content', sa.String(length=600), nullable=True),
    sa.Column('date_posted', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_author'), 'comments', ['author'], unique=False)
    op.create_index(op.f('ix_comments_content'), 'comments', ['content'], unique=False)
    op.create_index(op.f('ix_comments_date_posted'), 'comments', ['date_posted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_date_posted'), table_name='comments')
    op.drop_index(op.f('ix_comments_content'), table_name='comments')
    op.drop_index(op.f('ix_comments_author'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
